services:
  frontend:
    image: my-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable live reloading
    depends_on:
      - backend

  backend:
    image: my-backend
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - .env 